### PR TITLE
Support PHP 8.0

### PR DESCRIPTION
**Pull request by leoloso**
I'm running PHP 8 in my server, so I submit this simple PR to add support for it.

I deployed it already (pointing to my feature branch) to my site in production, and it works alright.

Please notice: PHP 8.0 doesn't work for development, since the `require-dev`ed package [`codeclimate/php-test-reporter`](https://packagist.org/packages/codeclimate/php-test-reporter) is stuck on PHP 7.

### CODE REVIEW

**Comment by leoloso** [comment]
Thanks @jenkoian. Do you plan to create a new tag?

**Comment by jenkoian** [comment]
@leoloso yep, just removing that codeclimate stuff, tag should be done within an hour.

**Comment by leoloso** [comment]
Lovely, thanks

**Comment by jenkoian** [comment]
@leoloso https://github.com/boxuk/wp-muplugin-loader/releases/tag/1.5.0

**Comment by leoloso** [comment]
Beautiful, thanks!

**Pull request merged**
